version: '3.8'
services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/app/backend_static
      - media_value:/app/backend_media

    depends_on:
      - django

  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    env_file:
      - ../backend/foodgram/.env

    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:

    build:
      context: ../backend
      dockerfile: Dockerfile

    restart: always
    volumes:
      - static_value:/app/backend_static
      - media_value:/app/backend_media
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && source create_superuser_prod.sh 
      && source create_user1.sh
      && source create_user_2.sh
      && python manage.py import_ingredients 
      && python manage.py import_tags
      && python manage.py collectstatic --no-input 
      && gunicorn --bind 0:8000 foodgram.wsgi"

    depends_on:
      - db
    env_file:
      - ../backend/foodgram/.env

volumes:
    static_value:
    media_value:
    postgres_data:
    result_build: