# Generated by Django 3.2 on 2023-09-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Пример: Завтрак, Обед, Ужин', max_length=64, unique=True, verbose_name='Тэг'),
        ),
    ]
